[package]
name = "mqtt_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
flowsdk = { path = ".." }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
