[package]
name = "flowsdk_ffi"
version = "0.4.2"
edition = "2021"
description = "FFI bindings for FlowSDK, allowing multi-language integration."
license = "MPL-2.0"
repository = "https://github.com/emqx/flowsdk"
documentation = "https://docs.rs/flowsdk_ffi"
keywords = ["ffi", "mqtt", "bindings"]
categories = ["api-bindings"]

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
flowsdk = { path = "..", version = "0.4.1" }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
uniffi = { version = "0.28", features = ["cli"] }
uniffi_macros = "0.28"
serde_json = "1.0"
rustls = { version = "0.23", optional = true }
rustls-pemfile = { version = "2.1", optional = true }
rustls-native-certs = { version = "0.7", optional = true }
quinn-proto = { version = "0.11", optional = true }
rustls-pki-types = { version = "1", optional = true }

[features]
default = ["tls", "quic"]
quic = ["tls", "flowsdk/quic", "dep:quinn-proto"]
tls = ["flowsdk/rustls-tls", "dep:rustls", "dep:rustls-native-certs", "dep:rustls-pemfile", "dep:rustls-pki-types"]
